name: BRANCH develop same repo                             
on: push    
    branches:
      - develop                                              
jobs:        
  use-your-own-action:
    name: Say Hi using your own action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      
      - uses: ./
        with:
         user: 'DÃ©borah'
